# -*- coding: utf-8 -*-
"""Areacircle.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1T5Mym7RX5fqMZTJrKknc3KkiVf0oB61c
"""

r=int(input("Enter the radius : "))
area=3.14*r*r
print("Area of the circle is : ",area)