# -*- coding: utf-8 -*-
"""CO1 (16).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LEdcmkA3IfFLZmCpUtGJ0L24aLF4EXZP
"""

str1="Happy"
str2="Christmas"
print("BEFORE")
print(str1+" "+str2)
print(" ")
str3=""
a=list(str1)
b=list(str2)
c=[]
d=[" "]
temp1=[]
temp2=[]
temp1=a[1]
temp2=b[1]
a[1]=temp2
b[1]=temp1
c=a+d+b
le=len(c)
for i in range(0,le,1):
  str3+=c[i]
print("AFTER")
print(str3)