# -*- coding: utf-8 -*-
"""Colortolist.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1549EniO5PdrQJgp26kbxajd5pFWMuujj
"""

n=int(input("Enter the number of colors: "))
list_color=[]
string=input("Enter above number of colors separated with coma(,) : ")
string1=string.split(",")
for i in range(0,n,1):
 list_color.append(string1[i])
print("The first color is: ",list_color[0])
print("The last color is : ",list_color[n-1])