# -*- coding: utf-8 -*-
"""Lambda function.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hgVJZdvLJTHno3gmOdfhQ9pgMoLcxpsN
"""

from ast import Return
ch=int(input("1.Area of Square\n2.Area of rectangle \n3.Area of triangle\nSelect your choice: "))
if(ch==1):
  n=int(input("Enter the lengt of the square: "))
  ar=lambda a : a*a
  print("Area= ",ar(n))
elif(ch==2):
  l=int(input("Enter the length of rectangle: "))
  b=int(input("Enter the bridth of the rectangle: "))
  ar=lambda l,b : l*b
  print("Area= ",ar(l,b))
elif(ch==3):
  h=int(input("Enter the height of triangle: "))
  b=int(input("Enter the bridth of the triangle: "))
  ar=lambda h,b : h*b*0.5
  print("Area= ",ar(h,b))
else:
  print("Invalid selection")