# -*- coding: utf-8 -*-
"""Over100.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jpgBP0eid5N1HU7ASV5OIMBlzVcxBygu
"""

n=int(input("Enter how many numbers are you want to input: "))
arr=[]
for i in range(0,n,1):
  elm=int(input("Enter the number : "))
  arr.append(elm)
print("The in puted numbers are")
for i in range(0,n,1):
  if(arr[i]>=100):
    print("over")
  else:
    print(arr[i])