# -*- coding: utf-8 -*-
"""Stringreplace.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dJfo-bMmrL_wdjDXWbszJtovsHDc5Spa
"""

name=input("Enter a string in small letter: ")
a=name[0]
l=len(name)
name1=name.replace(a,'$')
print(name[0],name1[1:l])