# -*- coding: utf-8 -*-
"""Tuplemark.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gyDKvQQX-pqVQnNZ7PKBbUwzVVMuhTgx
"""

tup_mark=(11,23.6,77.8,55,12.4)
print("Maximum mark  ")
print("-------------")
print(max(tup_mark))
print("")
print("Minimum mark  ")
print("-------------")
print(min(tup_mark))